@echo off
echo Running database migrations...
yarn prisma migrate deploy

echo Setting up admin user...
yarn setup-admin

echo Building application...
yarn build

echo Starting application...
yarn start
